controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_submit_user_form:
    path: '/submit-form'
    controller: 'App\Controller\UsersPageController::submitUserForm'
    methods: ['POST']